CREATE TABLE NUMBER(ID INT PRIMARY KEY, REFERP INT, REFERQ INT, TYPE_LETTER VARCHAR(10) );

INSERT INTO NUMBER (ID, REFERP, REFERQ, TYPE_LETTER)
              VALUES ('221', '1', null, 'p' );
              
INSERT INTO NUMBER (ID, REFERP, REFERQ, TYPE_LETTER)
              VALUES ('222', '1', null, 'p');
              
INSERT INTO NUMBER (ID, REFERP, REFERQ, TYPE_LETTER)
			VALUES ('223', null, '3', 'q');

INSERT INTO NUMBER (ID, REFERP, REFERQ, TYPE_LETTER)
              VALUES ('224', null, '4', 'q');
